# Generated by Django 5.2.17 on 2026-10-03 11:31

from django.db import migrations, models


def normalize_reserved_listings(apps, schema_editor):
    listing_model = apps.get_model('core', 'Listing')
    listing_model.objects.using(schema_editor.connection.alias).filter(
        status='RESERVED'
    ).update(status='AVAILABLE')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_favorite_message_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_reserved_listings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=10),
        ),
    ]
