# Generated by Django 5.2.17 on 2026-10-03 11:41

import django.db.models.deletion
from django.db import migrations, models


def categorize_existing_listings(apps, schema_editor):
    category_model = apps.get_model('core', 'Category')
    listing_model = apps.get_model('core', 'Listing')
    database = schema_editor.connection.alias
    uncategorized_listings = listing_model.objects.using(database).filter(category__isnull=True)
    if not uncategorized_listings.exists():
        return

    category = category_model.objects.using(database).filter(name='Uncategorized').first()
    if category is None:
        slug = 'uncategorized'
        suffix = 1
        while category_model.objects.using(database).filter(slug=slug).exists():
            slug = f'uncategorized-{suffix}'
            suffix += 1
        category = category_model.objects.using(database).create(
            name='Uncategorized',
            slug=slug,
        )
    uncategorized_listings.update(category_id=category.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_listing_status'),
    ]

    operations = [
        migrations.RunPython(categorize_existing_listings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='core.category'),
        ),
    ]
