# Generated by Django 5.2.17 on 2026-10-03 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_listing_category'),
    ]

    def normalize_conditions(apps, schema_editor):
        listing_model = apps.get_model('core', 'Listing')
        database = schema_editor.connection.alias
        listing_model.objects.using(database).filter(condition='New').update(condition='Brand New')
        listing_model.objects.using(database).filter(condition='Fair').update(condition='Fair Use')

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Fair Use', 'Fair Use'), ('Books & Notes', 'Books & Notes')], max_length=20),
        ),
        migrations.RunPython(normalize_conditions, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.conversation')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'rater'), name='unique_conversation_rater_review'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='rating_score_between_one_and_five')],
            },
        ),
    ]
